adapter_name_or_path: saves/LLaMA3-8B-Chinese-Chat/lora/train_2024-07-31-09-28-46-c4-1e5-20epoch
cutoff_len: 1024
dataset: alpaca_GJB5000B_20240730V1
dataset_dir: data
ddp_timeout: 180000000
do_train: true
finetuning_type: lora
flash_attn: auto
fp16: true
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 1.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 1000
model_name_or_path: ./models/Llama3-8B-Chinese-Chat
num_train_epochs: 5.0
optim: adamw_torch
output_dir: saves/LLaMA3-8B-Chinese-Chat/lora/train_2024-08-13-14-28-46-c4-1e5-20epoch
packing: false
per_device_train_batch_size: 4
plot_loss: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
report_to: none
save_steps: 100
stage: sft
template: llama3
use_dora: true
warmup_steps: 0
overwrite_output_dir: true